#!/usr/bin/env bash
# zone transfer

set -x
#set -e

_get_ns_records () {
	awk '
$4=="NS" && !record[tolower($1 "@" $5)]++ {
	printf("%s\t%s\n", tolower($1), tolower($5))
}
'
}

_was_successful () {
	local zonefile="$1"

	if test -s "$zonefile" && ! grep -iq -E '(transfer failed|connection refused|communications error|network unreachable|host unreachable|connection timed out|no servers could be reached)' "$zonefile"; then
		return 0
	else
		return 1
	fi
}

_zone_transfer () {
	local domain="$1"
	local nameserver="$2"
	local output_file="$output_dir/$domain@$nameserver.txt"

	#if test -e "$output_file"; then
	#	return
	#fi

	local tmp="`mktemp --tmpdir=/dev/shm/`"
	$dig AXFR $domain @$nameserver $dig_args > "$tmp"

	if _was_successful "$tmp"; then
		test -e "$output_file" \
			&& mv -f -- "$output_file" "$output_file.old"
		mv "$tmp" "$output_file"
		#mv --backup=numbered "$tmp" "$output_file"

		# TODO: history evaluation
		#test -e "$output_file.old" \
		#	&& diff "$output_file" "$output_file.old"

		# TODO: scan recursively
		#_get_ns_records < "$output_file" | while read DOMAIN NAMESERVER; do
		#	_zone_transfer $DOMAIN $NAMESERVER
		#done
	else
		rm -f -- "$tmp"
	fi
}

_start_walk () {
	local tld="$1"
	local root_server="$2"
	# get top level domain nameserver
	$dig NS $tld @$root_server $dig_args | _get_ns_records | while read DOMAIN NAMESERVER; do
		_zone_transfer $DOMAIN $NAMESERVER
	done
}

TLD="$1."
ROOT_SERVER="$2"

output_dir="zonefiles"
mkdir -p "$output_dir" || exit

dig=`command -v dig` || dig="/usr/bin/dig"
dig_args="+nocomments +nocmd +noquestion +nostats +time=15"

if test $ROOT_SERVER; then
	_start_walk $TLD $ROOT_SERVER
else
	# get dns root nameserver
	$dig NS . +short | while read ROOT_SERVER; do
		_start_walk $TLD $ROOT_SERVER
	done
fi

